### ISSUE TITLE
Class inheritance is not working as explained.

### ISSUE THREAD

**Issue by jerryyanmj** [kmashint/akme-js#1]
In the akme-core file, there is a doc explaining how extendClass works.
  /**
     \* Extends a given contructFcn() to be an instanceof superClass.
     \* The superClass may be a function or an object, the latter if it is intended to be the constructFcn.prototype.
     \* This also creates a relationship such that this.constructor.constructor is the superClass constructor.
     \* So given  var car = new cnep.extendClass(Car, Vehicle);  then  car.constructor.constructor === Vehicle  .
     */

I did a test, but it does not work as expected.

function car() {}
function Vehicle() {}
var car = new akme.extendClass(car, Vehicle);
car.constructor.constructor
==> Return
Function() { [native code] }

===> I thought it should be Vehicle ?

**Comment by kmashint** [comment]
This works, so the documentation needs some clarification.
`
function MyCar() {}
function MyVehicle() {}
akme.extendClass(MyCar, MyVehicle);
console.log("(new MyCar()).constructor.constructor ", (new MyCar()).constructor.constructor === MyVehicle);
`

**Comment by jerryyanmj** [comment]
Thanks.
